#Scrabble ver.alpha
#Program zczytuje litey z pól i wybiera najlepiej punktowane rozwiązanie
#Plansza 15x15 pól.

from tkinter import *

class Application(Frame):
    """Ramka od kalkulatora."""
    def __init__(self, master):
        super(Application, self).__init__(master)
        self.grid()
        self.create_widgets()

    def create_widgets(self):
        """Tworzenie planszy do gry."""
        alfabet = "abcdefghijklmnopr"
        #Stworzenie poziomego wiersza numerującego kolumny
        for i in range(1,16):
            Label(self, text = str(i), font=("Courier", 20)).grid(row = 0, column = int(i), sticky = N)
        #Stworzenie pionowego wiersza nazywającego wiersze
        for i in range(1,16):
            Label(self, text = alfabet[i-1], font=("Courier", 20)).grid(row = int(i), column = 0, sticky = N)
        #Lista wszystkich pól
        pole1a = Entry(self, width = 2, font=("Courier", 20)).grid(row = 1, column = 1)
        pole1b = Entry(self, width = 2, font=("Courier", 20)).grid(row = 1, column = 2)
        pole1c = Entry(self, width = 2, font=("Courier", 20)).grid(row = 1, column = 3)
        pole1d = Entry(self, width = 2, font=("Courier", 20)).grid(row = 1, column = 4)
        pole1e = Entry(self, width = 2, font=("Courier", 20)).grid(row = 1, column = 5)
        pole1f = Entry(self, width = 2, font=("Courier", 20)).grid(row = 1, column = 6)
        pole1g = Entry(self, width = 2, font=("Courier", 20)).grid(row = 1, column = 7)
        pole1h = Entry(self, width = 2, font=("Courier", 20)).grid(row = 1, column = 8)
        pole1i = Entry(self, width = 2, font=("Courier", 20)).grid(row = 1, column = 9)
        pole1j = Entry(self, width = 2, font=("Courier", 20)).grid(row = 1, column = 10)
        pole1k = Entry(self, width = 2, font=("Courier", 20)).grid(row = 1, column = 11)
        pole1l = Entry(self, width = 2, font=("Courier", 20)).grid(row = 1, column = 12)
        pole1m = Entry(self, width = 2, font=("Courier", 20)).grid(row = 1, column = 13)
        pole1n = Entry(self, width = 2, font=("Courier", 20)).grid(row = 1, column = 14)
        pole1o = Entry(self, width = 2, font=("Courier", 20)).grid(row = 1, column = 15)
        pole2a = Entry(self, width = 2, font=("Courier", 20)).grid(row = 2, column = 1)
        pole2b = Entry(self, width = 2, font=("Courier", 20)).grid(row = 2, column = 2)
        pole2c = Entry(self, width = 2, font=("Courier", 20)).grid(row = 2, column = 3)
        pole2d = Entry(self, width = 2, font=("Courier", 20)).grid(row = 2, column = 4)
        pole2e = Entry(self, width = 2, font=("Courier", 20)).grid(row = 2, column = 5)
        pole2f = Entry(self, width = 2, font=("Courier", 20)).grid(row = 2, column = 6)
        pole2g = Entry(self, width = 2, font=("Courier", 20)).grid(row = 2, column = 7)
        pole2h = Entry(self, width = 2, font=("Courier", 20)).grid(row = 2, column = 8)
        pole2i = Entry(self, width = 2, font=("Courier", 20)).grid(row = 2, column = 9)
        pole2j = Entry(self, width = 2, font=("Courier", 20)).grid(row = 2, column = 10)
        pole2k = Entry(self, width = 2, font=("Courier", 20)).grid(row = 2, column = 11)
        pole2l = Entry(self, width = 2, font=("Courier", 20)).grid(row = 2, column = 12)
        pole2m = Entry(self, width = 2, font=("Courier", 20)).grid(row = 2, column = 13)
        pole2n = Entry(self, width = 2, font=("Courier", 20)).grid(row = 2, column = 14)
        pole2o = Entry(self, width = 2, font=("Courier", 20)).grid(row = 2, column = 15)
        pole3a = Entry(self, width = 2, font=("Courier", 20)).grid(row = 3, column = 1)
        pole3b = Entry(self, width = 2, font=("Courier", 20)).grid(row = 3, column = 2)
        pole3c = Entry(self, width = 2, font=("Courier", 20)).grid(row = 3, column = 3)
        pole3d = Entry(self, width = 2, font=("Courier", 20)).grid(row = 3, column = 4)
        pole3e = Entry(self, width = 2, font=("Courier", 20)).grid(row = 3, column = 5)
        pole3f = Entry(self, width = 2, font=("Courier", 20)).grid(row = 3, column = 6)
        pole3g = Entry(self, width = 2, font=("Courier", 20)).grid(row = 3, column = 7)
        pole3h = Entry(self, width = 2, font=("Courier", 20)).grid(row = 3, column = 8)
        pole3i = Entry(self, width = 2, font=("Courier", 20)).grid(row = 3, column = 9)
        pole3j = Entry(self, width = 2, font=("Courier", 20)).grid(row = 3, column = 10)
        pole3k = Entry(self, width = 2, font=("Courier", 20)).grid(row = 3, column = 11)
        pole3l = Entry(self, width = 2, font=("Courier", 20)).grid(row = 3, column = 12)
        pole3m = Entry(self, width = 2, font=("Courier", 20)).grid(row = 3, column = 13)
        pole3n = Entry(self, width = 2, font=("Courier", 20)).grid(row = 3, column = 14)
        pole3o = Entry(self, width = 2, font=("Courier", 20)).grid(row = 3, column = 15)
        pole4a = Entry(self, width = 2, font=("Courier", 20)).grid(row = 4, column = 1)
        pole4b = Entry(self, width = 2, font=("Courier", 20)).grid(row = 4, column = 2)
        pole4c = Entry(self, width = 2, font=("Courier", 20)).grid(row = 4, column = 3)
        pole4d = Entry(self, width = 2, font=("Courier", 20)).grid(row = 4, column = 4)
        pole4e = Entry(self, width = 2, font=("Courier", 20)).grid(row = 4, column = 5)
        pole4f = Entry(self, width = 2, font=("Courier", 20)).grid(row = 4, column = 6)
        pole4g = Entry(self, width = 2, font=("Courier", 20)).grid(row = 4, column = 7)
        pole4h = Entry(self, width = 2, font=("Courier", 20)).grid(row = 4, column = 8)
        pole4i = Entry(self, width = 2, font=("Courier", 20)).grid(row = 4, column = 9)
        pole4j = Entry(self, width = 2, font=("Courier", 20)).grid(row = 4, column = 10)
        pole4k = Entry(self, width = 2, font=("Courier", 20)).grid(row = 4, column = 11)
        pole4l = Entry(self, width = 2, font=("Courier", 20)).grid(row = 4, column = 12)
        pole4m = Entry(self, width = 2, font=("Courier", 20)).grid(row = 4, column = 13)
        pole4n = Entry(self, width = 2, font=("Courier", 20)).grid(row = 4, column = 14)
        pole4o = Entry(self, width = 2, font=("Courier", 20)).grid(row = 4, column = 15)
        pole5a = Entry(self, width = 2, font=("Courier", 20)).grid(row = 5, column = 1)
        pole5b = Entry(self, width = 2, font=("Courier", 20)).grid(row = 5, column = 2)
        pole5c = Entry(self, width = 2, font=("Courier", 20)).grid(row = 5, column = 3)
        pole5d = Entry(self, width = 2, font=("Courier", 20)).grid(row = 5, column = 4)
        pole5e = Entry(self, width = 2, font=("Courier", 20)).grid(row = 5, column = 5)
        pole5f = Entry(self, width = 2, font=("Courier", 20)).grid(row = 5, column = 6)
        pole5g = Entry(self, width = 2, font=("Courier", 20)).grid(row = 5, column = 7)
        pole5h = Entry(self, width = 2, font=("Courier", 20)).grid(row = 5, column = 8)
        pole5i = Entry(self, width = 2, font=("Courier", 20)).grid(row = 5, column = 9)
        pole5j = Entry(self, width = 2, font=("Courier", 20)).grid(row = 5, column = 10)
        pole5k = Entry(self, width = 2, font=("Courier", 20)).grid(row = 5, column = 11)
        pole5l = Entry(self, width = 2, font=("Courier", 20)).grid(row = 5, column = 12)
        pole5m = Entry(self, width = 2, font=("Courier", 20)).grid(row = 5, column = 13)
        pole5n = Entry(self, width = 2, font=("Courier", 20)).grid(row = 5, column = 14)
        pole5o = Entry(self, width = 2, font=("Courier", 20)).grid(row = 5, column = 15)
        pole6a = Entry(self, width = 2, font=("Courier", 20)).grid(row = 6, column = 1)
        pole6b = Entry(self, width = 2, font=("Courier", 20)).grid(row = 6, column = 2)
        pole6c = Entry(self, width = 2, font=("Courier", 20)).grid(row = 6, column = 3)
        pole6d = Entry(self, width = 2, font=("Courier", 20)).grid(row = 6, column = 4)
        pole6e = Entry(self, width = 2, font=("Courier", 20)).grid(row = 6, column = 5)
        pole6f = Entry(self, width = 2, font=("Courier", 20)).grid(row = 6, column = 6)
        pole6g = Entry(self, width = 2, font=("Courier", 20)).grid(row = 6, column = 7)
        pole6h = Entry(self, width = 2, font=("Courier", 20)).grid(row = 6, column = 8)
        pole6i = Entry(self, width = 2, font=("Courier", 20)).grid(row = 6, column = 9)
        pole6j = Entry(self, width = 2, font=("Courier", 20)).grid(row = 6, column = 10)
        pole6k = Entry(self, width = 2, font=("Courier", 20)).grid(row = 6, column = 11)
        pole6l = Entry(self, width = 2, font=("Courier", 20)).grid(row = 6, column = 12)
        pole6m = Entry(self, width = 2, font=("Courier", 20)).grid(row = 6, column = 13)
        pole6n = Entry(self, width = 2, font=("Courier", 20)).grid(row = 6, column = 14)
        pole6o = Entry(self, width = 2, font=("Courier", 20)).grid(row = 6, column = 15)
        pole7a = Entry(self, width = 2, font=("Courier", 20)).grid(row = 7, column = 1)
        pole7b = Entry(self, width = 2, font=("Courier", 20)).grid(row = 7, column = 2)
        pole7c = Entry(self, width = 2, font=("Courier", 20)).grid(row = 7, column = 3)
        pole7d = Entry(self, width = 2, font=("Courier", 20)).grid(row = 7, column = 4)
        pole7e = Entry(self, width = 2, font=("Courier", 20)).grid(row = 7, column = 5)
        pole7f = Entry(self, width = 2, font=("Courier", 20)).grid(row = 7, column = 6)
        pole7g = Entry(self, width = 2, font=("Courier", 20)).grid(row = 7, column = 7)
        pole7h = Entry(self, width = 2, font=("Courier", 20)).grid(row = 7, column = 8)
        pole7i = Entry(self, width = 2, font=("Courier", 20)).grid(row = 7, column = 9)
        pole7j = Entry(self, width = 2, font=("Courier", 20)).grid(row = 7, column = 10)
        pole7k = Entry(self, width = 2, font=("Courier", 20)).grid(row = 7, column = 11)
        pole7l = Entry(self, width = 2, font=("Courier", 20)).grid(row = 7, column = 12)
        pole7m = Entry(self, width = 2, font=("Courier", 20)).grid(row = 7, column = 13)
        pole7n = Entry(self, width = 2, font=("Courier", 20)).grid(row = 7, column = 14)
        pole7o = Entry(self, width = 2, font=("Courier", 20)).grid(row = 7, column = 15)
        pole8a = Entry(self, width = 2, font=("Courier", 20)).grid(row = 8, column = 1)
        pole8b = Entry(self, width = 2, font=("Courier", 20)).grid(row = 8, column = 2)
        pole8c = Entry(self, width = 2, font=("Courier", 20)).grid(row = 8, column = 3)
        pole8d = Entry(self, width = 2, font=("Courier", 20)).grid(row = 8, column = 4)
        pole8e = Entry(self, width = 2, font=("Courier", 20)).grid(row = 8, column = 5)
        pole8f = Entry(self, width = 2, font=("Courier", 20)).grid(row = 8, column = 6)
        pole8g = Entry(self, width = 2, font=("Courier", 20)).grid(row = 8, column = 7)
        pole8h = Entry(self, width = 2, font=("Courier", 20)).grid(row = 8, column = 8)
        pole8i = Entry(self, width = 2, font=("Courier", 20)).grid(row = 8, column = 9)
        pole8j = Entry(self, width = 2, font=("Courier", 20)).grid(row = 8, column = 10)
        pole8k = Entry(self, width = 2, font=("Courier", 20)).grid(row = 8, column = 11)
        pole8l = Entry(self, width = 2, font=("Courier", 20)).grid(row = 8, column = 12)
        pole8m = Entry(self, width = 2, font=("Courier", 20)).grid(row = 8, column = 13)
        pole8n = Entry(self, width = 2, font=("Courier", 20)).grid(row = 8, column = 14)
        pole8o = Entry(self, width = 2, font=("Courier", 20)).grid(row = 8, column = 15)
        pole9a = Entry(self, width = 2, font=("Courier", 20)).grid(row = 9, column = 1)
        pole9b = Entry(self, width = 2, font=("Courier", 20)).grid(row = 9, column = 2)
        pole9c = Entry(self, width = 2, font=("Courier", 20)).grid(row = 9, column = 3)
        pole9d = Entry(self, width = 2, font=("Courier", 20)).grid(row = 9, column = 4)
        pole9e = Entry(self, width = 2, font=("Courier", 20)).grid(row = 9, column = 5)
        pole9f = Entry(self, width = 2, font=("Courier", 20)).grid(row = 9, column = 6)
        pole9g = Entry(self, width = 2, font=("Courier", 20)).grid(row = 9, column = 7)
        pole9h = Entry(self, width = 2, font=("Courier", 20)).grid(row = 9, column = 8)
        pole9i = Entry(self, width = 2, font=("Courier", 20)).grid(row = 9, column = 9)
        pole9j = Entry(self, width = 2, font=("Courier", 20)).grid(row = 9, column = 10)
        pole9k = Entry(self, width = 2, font=("Courier", 20)).grid(row = 9, column = 11)
        pole9l = Entry(self, width = 2, font=("Courier", 20)).grid(row = 9, column = 12)
        pole9m = Entry(self, width = 2, font=("Courier", 20)).grid(row = 9, column = 13)
        pole9n = Entry(self, width = 2, font=("Courier", 20)).grid(row = 9, column = 14)
        pole9o = Entry(self, width = 2, font=("Courier", 20)).grid(row = 9, column = 15)
        pole10a = Entry(self, width = 2, font=("Courier", 20)).grid(row = 10, column = 1)
        pole10b = Entry(self, width = 2, font=("Courier", 20)).grid(row = 10, column = 2)
        pole10c = Entry(self, width = 2, font=("Courier", 20)).grid(row = 10, column = 3)
        pole10d = Entry(self, width = 2, font=("Courier", 20)).grid(row = 10, column = 4)
        pole10e = Entry(self, width = 2, font=("Courier", 20)).grid(row = 10, column = 5)
        pole10f = Entry(self, width = 2, font=("Courier", 20)).grid(row = 10, column = 6)
        pole10g = Entry(self, width = 2, font=("Courier", 20)).grid(row = 10, column = 7)
        pole10h = Entry(self, width = 2, font=("Courier", 20)).grid(row = 10, column = 8)
        pole10i = Entry(self, width = 2, font=("Courier", 20)).grid(row = 10, column = 9)
        pole10j = Entry(self, width = 2, font=("Courier", 20)).grid(row = 10, column = 10)
        pole10k = Entry(self, width = 2, font=("Courier", 20)).grid(row = 10, column = 11)
        pole10l = Entry(self, width = 2, font=("Courier", 20)).grid(row = 10, column = 12)
        pole10m = Entry(self, width = 2, font=("Courier", 20)).grid(row = 10, column = 13)
        pole10n = Entry(self, width = 2, font=("Courier", 20)).grid(row = 10, column = 14)
        pole10o = Entry(self, width = 2, font=("Courier", 20)).grid(row = 10, column = 15)
        pole11a = Entry(self, width = 2, font=("Courier", 20)).grid(row = 11, column = 1)
        pole11b = Entry(self, width = 2, font=("Courier", 20)).grid(row = 11, column = 2)
        pole11c = Entry(self, width = 2, font=("Courier", 20)).grid(row = 11, column = 3)
        pole11d = Entry(self, width = 2, font=("Courier", 20)).grid(row = 11, column = 4)
        pole11e = Entry(self, width = 2, font=("Courier", 20)).grid(row = 11, column = 5)
        pole11f = Entry(self, width = 2, font=("Courier", 20)).grid(row = 11, column = 6)
        pole11g = Entry(self, width = 2, font=("Courier", 20)).grid(row = 11, column = 7)
        pole11h = Entry(self, width = 2, font=("Courier", 20)).grid(row = 11, column = 8)
        pole11i = Entry(self, width = 2, font=("Courier", 20)).grid(row = 11, column = 9)
        pole11j = Entry(self, width = 2, font=("Courier", 20)).grid(row = 11, column = 10)
        pole11k = Entry(self, width = 2, font=("Courier", 20)).grid(row = 11, column = 11)
        pole11l = Entry(self, width = 2, font=("Courier", 20)).grid(row = 11, column = 12)
        pole11m = Entry(self, width = 2, font=("Courier", 20)).grid(row = 11, column = 13)
        pole11n = Entry(self, width = 2, font=("Courier", 20)).grid(row = 11, column = 14)
        pole11o = Entry(self, width = 2, font=("Courier", 20)).grid(row = 11, column = 15)
        pole12a = Entry(self, width = 2, font=("Courier", 20)).grid(row = 12, column = 1)
        pole12b = Entry(self, width = 2, font=("Courier", 20)).grid(row = 12, column = 2)
        pole12c = Entry(self, width = 2, font=("Courier", 20)).grid(row = 12, column = 3)
        pole12d = Entry(self, width = 2, font=("Courier", 20)).grid(row = 12, column = 4)
        pole12e = Entry(self, width = 2, font=("Courier", 20)).grid(row = 12, column = 5)
        pole12f = Entry(self, width = 2, font=("Courier", 20)).grid(row = 12, column = 6)
        pole12g = Entry(self, width = 2, font=("Courier", 20)).grid(row = 12, column = 7)
        pole12h = Entry(self, width = 2, font=("Courier", 20)).grid(row = 12, column = 8)
        pole12i = Entry(self, width = 2, font=("Courier", 20)).grid(row = 12, column = 9)
        pole12j = Entry(self, width = 2, font=("Courier", 20)).grid(row = 12, column = 10)
        pole12k = Entry(self, width = 2, font=("Courier", 20)).grid(row = 12, column = 11)
        pole12l = Entry(self, width = 2, font=("Courier", 20)).grid(row = 12, column = 12)
        pole12m = Entry(self, width = 2, font=("Courier", 20)).grid(row = 12, column = 13)
        pole12n = Entry(self, width = 2, font=("Courier", 20)).grid(row = 12, column = 14)
        pole12o = Entry(self, width = 2, font=("Courier", 20)).grid(row = 12, column = 15)
        pole13a = Entry(self, width = 2, font=("Courier", 20)).grid(row = 13, column = 1)
        pole13b = Entry(self, width = 2, font=("Courier", 20)).grid(row = 13, column = 2)
        pole13c = Entry(self, width = 2, font=("Courier", 20)).grid(row = 13, column = 3)
        pole13d = Entry(self, width = 2, font=("Courier", 20)).grid(row = 13, column = 4)
        pole13e = Entry(self, width = 2, font=("Courier", 20)).grid(row = 13, column = 5)
        pole13f = Entry(self, width = 2, font=("Courier", 20)).grid(row = 13, column = 6)
        pole13g = Entry(self, width = 2, font=("Courier", 20)).grid(row = 13, column = 7)
        pole13h = Entry(self, width = 2, font=("Courier", 20)).grid(row = 13, column = 8)
        pole13i = Entry(self, width = 2, font=("Courier", 20)).grid(row = 13, column = 9)
        pole13j = Entry(self, width = 2, font=("Courier", 20)).grid(row = 13, column = 10)
        pole13k = Entry(self, width = 2, font=("Courier", 20)).grid(row = 13, column = 11)
        pole13l = Entry(self, width = 2, font=("Courier", 20)).grid(row = 13, column = 12)
        pole13m = Entry(self, width = 2, font=("Courier", 20)).grid(row = 13, column = 13)
        pole13n = Entry(self, width = 2, font=("Courier", 20)).grid(row = 13, column = 14)
        pole13o = Entry(self, width = 2, font=("Courier", 20)).grid(row = 13, column = 15)
        pole14a = Entry(self, width = 2, font=("Courier", 20)).grid(row = 14, column = 1)
        pole14b = Entry(self, width = 2, font=("Courier", 20)).grid(row = 14, column = 2)
        pole14c = Entry(self, width = 2, font=("Courier", 20)).grid(row = 14, column = 3)
        pole14d = Entry(self, width = 2, font=("Courier", 20)).grid(row = 14, column = 4)
        pole14e = Entry(self, width = 2, font=("Courier", 20)).grid(row = 14, column = 5)
        pole14f = Entry(self, width = 2, font=("Courier", 20)).grid(row = 14, column = 6)
        pole14g = Entry(self, width = 2, font=("Courier", 20)).grid(row = 14, column = 7)
        pole14h = Entry(self, width = 2, font=("Courier", 20)).grid(row = 14, column = 8)
        pole14i = Entry(self, width = 2, font=("Courier", 20)).grid(row = 14, column = 9)
        pole14j = Entry(self, width = 2, font=("Courier", 20)).grid(row = 14, column = 10)
        pole14k = Entry(self, width = 2, font=("Courier", 20)).grid(row = 14, column = 11)
        pole14l = Entry(self, width = 2, font=("Courier", 20)).grid(row = 14, column = 12)
        pole14m = Entry(self, width = 2, font=("Courier", 20)).grid(row = 14, column = 13)
        pole14n = Entry(self, width = 2, font=("Courier", 20)).grid(row = 14, column = 14)
        pole14o = Entry(self, width = 2, font=("Courier", 20)).grid(row = 14, column = 15)
        pole15a = Entry(self, width = 2, font=("Courier", 20)).grid(row = 15, column = 1)
        pole15b = Entry(self, width = 2, font=("Courier", 20)).grid(row = 15, column = 2)
        pole15c = Entry(self, width = 2, font=("Courier", 20)).grid(row = 15, column = 3)
        pole15d = Entry(self, width = 2, font=("Courier", 20)).grid(row = 15, column = 4)
        pole15e = Entry(self, width = 2, font=("Courier", 20)).grid(row = 15, column = 5)
        pole15f = Entry(self, width = 2, font=("Courier", 20)).grid(row = 15, column = 6)
        pole15g = Entry(self, width = 2, font=("Courier", 20)).grid(row = 15, column = 7)
        pole15h = Entry(self, width = 2, font=("Courier", 20)).grid(row = 15, column = 8)
        pole15i = Entry(self, width = 2, font=("Courier", 20)).grid(row = 15, column = 9)
        pole15j = Entry(self, width = 2, font=("Courier", 20)).grid(row = 15, column = 10)
        pole15k = Entry(self, width = 2, font=("Courier", 20)).grid(row = 15, column = 11)
        pole15l = Entry(self, width = 2, font=("Courier", 20)).grid(row = 15, column = 12)
        pole15m = Entry(self, width = 2, font=("Courier", 20)).grid(row = 15, column = 13)
        pole15n = Entry(self, width = 2, font=("Courier", 20)).grid(row = 15, column = 14)
        pole15o = Entry(self, width = 2, font=("Courier", 20)).grid(row = 15, column = 15)

root = Tk()
root.title("Kalkulator")
root.geometry("415x540")

app = Application(root)

root.mainloop()
