#Scrabble ver.alpha
#Program zczytuje litey z pól i wybiera najlepiej punktowane rozwiązanie
#Plansza 15x15 pól.

from tkinter import *

class Application(Frame):
    """Ramka od kalkulatora."""
    def __init__(self, master):
        super(Application, self).__init__(master)
        self.grid()
        self.create_widgets()
        self.POLA = [self.pole1a,self.pole2a,self.pole3a,self.pole4a,self.pole5a,self.pole6a,self.pole7a,self.pole8a,self.pole9a,self.pole10a,self.pole11a,self.pole12a,self.pole13a,self.pole14a,self.pole15a,self.pole1b,self.pole2b,self.pole3b,self.pole4b,self.pole5b,self.pole6b,self.pole7b,self.pole8b,self.pole9b,self.pole10b,self.pole11b,self.pole12b,self.pole13b,self.pole14b,self.pole15b,self.pole1c,self.pole2c,self.pole3c,self.pole4c,self.pole5c,self.pole6c,self.pole7c,self.pole8c,self.pole9c,self.pole10c,self.pole11c,self.pole12c,self.pole13c,self.pole14c,self.pole15c,self.pole1d,self.pole2d,self.pole3d,self.pole4d,self.pole5d,self.pole6d,self.pole7d,self.pole8d,self.pole9d,self.pole10d,self.pole11d,self.pole12d,self.pole13d,self.pole14d,self.pole15d,self.pole1e,self.pole2e,self.pole3e,self.pole4e,self.pole5e,self.pole6e,self.pole7e,self.pole8e,self.pole9e,self.pole10e,self.pole11e,self.pole12e,self.pole13e,self.pole14e,self.pole15e,self.pole1f,self.pole2f,self.pole3f,self.pole4f,self.pole5f,self.pole6f,self.pole7f,self.pole8f,self.pole9f,self.pole10f,self.pole11f,self.pole12f,self.pole13f,self.pole14f,self.pole15f,self.pole1g,self.pole2g,self.pole3g,self.pole4g,self.pole5g,self.pole6g,self.pole7g,self.pole8g,self.pole9g,self.pole10g,self.pole11g,self.pole12g,self.pole13g,self.pole14g,self.pole15g,self.pole1h,self.pole2h,self.pole3h,self.pole4h,self.pole5h,self.pole6h,self.pole7h,self.pole8h,self.pole9h,self.pole10h,self.pole11h,self.pole12h,self.pole13h,self.pole14h,self.pole15h,self.pole1i,self.pole2i,self.pole3i,self.pole4i,self.pole5i,self.pole6i,self.pole7i,self.pole8i,self.pole9i,self.pole10i,self.pole11i,self.pole12i,self.pole13i,self.pole14i,self.pole15i,self.pole1j,self.pole2j,self.pole3j,self.pole4j,self.pole5j,self.pole6j,self.pole7j,self.pole8j,self.pole9j,self.pole10j,self.pole11j,self.pole12j,self.pole13j,self.pole14j,self.pole15j,self.pole1k,self.pole2k,self.pole3k,self.pole4k,self.pole5k,self.pole6k,self.pole7k,self.pole8k,self.pole9k,self.pole10k,self.pole11k,self.pole12k,self.pole13k,self.pole14k,self.pole15k,self.pole1l,self.pole2l,self.pole3l,self.pole4l,self.pole5l,self.pole6l,self.pole7l,self.pole8l,self.pole9l,self.pole10l,self.pole11l,self.pole12l,self.pole13l,self.pole14l,self.pole15l,self.pole1m,self.pole2m,self.pole3m,self.pole4m,self.pole5m,self.pole6m,self.pole7m,self.pole8m,self.pole9m,self.pole10m,self.pole11m,self.pole12m,self.pole13m,self.pole14m,self.pole15m,self.pole1n,self.pole2n,self.pole3n,self.pole4n,self.pole5n,self.pole6n,self.pole7n,self.pole8n,self.pole9n,self.pole10n,self.pole11n,self.pole12n,self.pole13n,self.pole14n,self.pole15n,self.pole1o,self.pole2o,self.pole3o,self.pole4o,self.pole5o,self.pole6o,self.pole7o,self.pole8o,self.pole9o,self.pole10o,self.pole11o,self.pole12o,self.pole13o,self.pole14o,self.pole15o]
        self.wyrazy = []
        self.litery = []

    def create_widgets(self):
        """Tworzenie planszy do gry."""
        alfabet = "abcdefghijklmnopr"
        #Stworzenie poziomego wiersza numerującego kolumny
        for i in range(1,16):
            Label(self, text = str(i), font=("Courier", 20)).grid(row = 0, column = int(i), sticky = N)
        #Stworzenie pionowego wiersza nazywającego wiersze
        for i in range(1,16):
            Label(self, text = alfabet[i-1], font=("Courier", 20)).grid(row = int(i), column = 0, sticky = N)
        #Lista wszystkich pól
            #Wiersz A
        self.pole1a = Entry(self, width = 2, font=("Courier", 20), bg = 'red')
        self.pole1a.grid(row = 1, column = 1)
        self.pole2a = Entry(self, width = 2, font=("Courier", 20))
        self.pole2a.grid(row = 1, column = 2)
        self.pole3a = Entry(self, width = 2, font=("Courier", 20))
        self.pole3a.grid(row = 1, column = 3)
        self.pole4a = Entry(self, width = 2, font=("Courier", 20), bg = 'cyan')
        self.pole4a.grid(row = 1, column = 4)
        self.pole5a = Entry(self, width = 2, font=("Courier", 20))
        self.pole5a.grid(row = 1, column = 5)
        self.pole6a = Entry(self, width = 2, font=("Courier", 20))
        self.pole6a.grid(row = 1, column = 6)
        self.pole7a = Entry(self, width = 2, font=("Courier", 20))
        self.pole7a.grid(row = 1, column = 7)
        self.pole8a = Entry(self, width = 2, font=("Courier", 20), bg = 'red')
        self.pole8a.grid(row = 1, column = 8)
        self.pole9a = Entry(self, width = 2, font=("Courier", 20))
        self.pole9a.grid(row = 1, column = 9)
        self.pole10a = Entry(self, width = 2, font=("Courier", 20))
        self.pole10a.grid(row = 1, column = 10)
        self.pole11a = Entry(self, width = 2, font=("Courier", 20))
        self.pole11a.grid(row = 1, column = 11)
        self.pole12a = Entry(self, width = 2, font=("Courier", 20), bg = 'cyan')
        self.pole12a.grid(row = 1, column = 12)
        self.pole13a = Entry(self, width = 2, font=("Courier", 20))
        self.pole13a.grid(row = 1, column = 13)
        self.pole14a = Entry(self, width = 2, font=("Courier", 20))
        self.pole14a.grid(row = 1, column = 14)
        self.pole15a = Entry(self, width = 2, font=("Courier", 20), bg = 'red')
        self.pole15a.grid(row = 1, column = 15)
            #Wiersz B
        self.pole1b = Entry(self, width = 2, font=("Courier", 20))
        self.pole1b.grid(row = 2, column = 1)
        self.pole2b = Entry(self, width = 2, font=("Courier", 20), bg = 'yellow')
        self.pole2b.grid(row = 2, column = 2)
        self.pole3b = Entry(self, width = 2, font=("Courier", 20))
        self.pole3b.grid(row = 2, column = 3)
        self.pole4b = Entry(self, width = 2, font=("Courier", 20))
        self.pole4b.grid(row = 2, column = 4)
        self.pole5b = Entry(self, width = 2, font=("Courier", 20))
        self.pole5b.grid(row = 2, column = 5)
        self.pole6b = Entry(self, width = 2, font=("Courier", 20), bg = 'cornflower blue')
        self.pole6b.grid(row = 2, column = 6)
        self.pole7b = Entry(self, width = 2, font=("Courier", 20))
        self.pole7b.grid(row = 2, column = 7)
        self.pole8b = Entry(self, width = 2, font=("Courier", 20))
        self.pole8b.grid(row = 2, column = 8)
        self.pole9b = Entry(self, width = 2, font=("Courier", 20))
        self.pole9b.grid(row = 2, column = 9)
        self.pole10b = Entry(self, width = 2, font=("Courier", 20), bg = 'cornflower blue')
        self.pole10b.grid(row = 2, column = 10)
        self.pole11b = Entry(self, width = 2, font=("Courier", 20))
        self.pole11b.grid(row = 2, column = 11)
        self.pole12b = Entry(self, width = 2, font=("Courier", 20))
        self.pole12b.grid(row = 2, column = 12)
        self.pole13b = Entry(self, width = 2, font=("Courier", 20))
        self.pole13b.grid(row = 2, column = 13)
        self.pole14b = Entry(self, width = 2, font=("Courier", 20), bg = 'yellow')
        self.pole14b.grid(row = 2, column = 14)
        self.pole15b = Entry(self, width = 2, font=("Courier", 20))
        self.pole15b.grid(row = 2, column = 15)
            #Wiersz C
        self.pole1c = Entry(self, width = 2, font=("Courier", 20))
        self.pole1c.grid(row = 3, column = 1)
        self.pole2c = Entry(self, width = 2, font=("Courier", 20))
        self.pole2c.grid(row = 3, column = 2)
        self.pole3c = Entry(self, width = 2, font=("Courier", 20), bg = 'yellow')
        self.pole3c.grid(row = 3, column = 3)
        self.pole4c = Entry(self, width = 2, font=("Courier", 20))
        self.pole4c.grid(row = 3, column = 4)
        self.pole5c = Entry(self, width = 2, font=("Courier", 20))
        self.pole5c.grid(row = 3, column = 5)
        self.pole6c = Entry(self, width = 2, font=("Courier", 20))
        self.pole6c.grid(row = 3, column = 6)
        self.pole7c = Entry(self, width = 2, font=("Courier", 20), bg = 'cyan')
        self.pole7c.grid(row = 3, column = 7)
        self.pole8c = Entry(self, width = 2, font=("Courier", 20))
        self.pole8c.grid(row = 3, column = 8)
        self.pole9c = Entry(self, width = 2, font=("Courier", 20), bg = 'cyan')
        self.pole9c.grid(row = 3, column = 9)
        self.pole10c = Entry(self, width = 2, font=("Courier", 20))
        self.pole10c.grid(row = 3, column = 10)
        self.pole11c = Entry(self, width = 2, font=("Courier", 20))
        self.pole11c.grid(row = 3, column = 11)
        self.pole12c = Entry(self, width = 2, font=("Courier", 20))
        self.pole12c.grid(row = 3, column = 12)
        self.pole13c = Entry(self, width = 2, font=("Courier", 20), bg = 'yellow')
        self.pole13c.grid(row = 3, column = 13)
        self.pole14c = Entry(self, width = 2, font=("Courier", 20))
        self.pole14c.grid(row = 3, column = 14)
        self.pole15c = Entry(self, width = 2, font=("Courier", 20))
        self.pole15c.grid(row = 3, column = 15)
            #Wiersz D
        self.pole1d = Entry(self, width = 2, font=("Courier", 20), bg = 'cyan')
        self.pole1d.grid(row = 4, column = 1)
        self.pole2d = Entry(self, width = 2, font=("Courier", 20))
        self.pole2d.grid(row = 4, column = 2)
        self.pole3d = Entry(self, width = 2, font=("Courier", 20))
        self.pole3d.grid(row = 4, column = 3)
        self.pole4d = Entry(self, width = 2, font=("Courier", 20), bg = 'yellow')
        self.pole4d.grid(row = 4, column = 4)
        self.pole5d = Entry(self, width = 2, font=("Courier", 20))
        self.pole5d.grid(row = 4, column = 5)
        self.pole6d = Entry(self, width = 2, font=("Courier", 20))
        self.pole6d.grid(row = 4, column = 6)
        self.pole7d = Entry(self, width = 2, font=("Courier", 20))
        self.pole7d.grid(row = 4, column = 7)
        self.pole8d = Entry(self, width = 2, font=("Courier", 20), bg = 'cyan')
        self.pole8d.grid(row = 4, column = 8)
        self.pole9d = Entry(self, width = 2, font=("Courier", 20))
        self.pole9d.grid(row = 4, column = 9)
        self.pole10d = Entry(self, width = 2, font=("Courier", 20))
        self.pole10d.grid(row = 4, column = 10)
        self.pole11d = Entry(self, width = 2, font=("Courier", 20))
        self.pole11d.grid(row = 4, column = 11)
        self.pole12d = Entry(self, width = 2, font=("Courier", 20), bg = 'yellow')
        self.pole12d.grid(row = 4, column = 12)
        self.pole13d = Entry(self, width = 2, font=("Courier", 20))
        self.pole13d.grid(row = 4, column = 13)
        self.pole14d = Entry(self, width = 2, font=("Courier", 20))
        self.pole14d.grid(row = 4, column = 14)
        self.pole15d = Entry(self, width = 2, font=("Courier", 20), bg = 'cyan')
        self.pole15d.grid(row = 4, column = 15)
            #Wiersz E
        self.pole1e = Entry(self, width = 2, font=("Courier", 20))
        self.pole1e.grid(row = 5, column = 1)
        self.pole2e = Entry(self, width = 2, font=("Courier", 20))
        self.pole2e.grid(row = 5, column = 2)
        self.pole3e = Entry(self, width = 2, font=("Courier", 20))
        self.pole3e.grid(row = 5, column = 3)
        self.pole4e = Entry(self, width = 2, font=("Courier", 20))
        self.pole4e.grid(row = 5, column = 4)
        self.pole5e = Entry(self, width = 2, font=("Courier", 20), bg = 'yellow')
        self.pole5e.grid(row = 5, column = 5)
        self.pole6e = Entry(self, width = 2, font=("Courier", 20))
        self.pole6e.grid(row = 5, column = 6)
        self.pole7e = Entry(self, width = 2, font=("Courier", 20))
        self.pole7e.grid(row = 5, column = 7)
        self.pole8e = Entry(self, width = 2, font=("Courier", 20))
        self.pole8e.grid(row = 5, column = 8)
        self.pole9e = Entry(self, width = 2, font=("Courier", 20))
        self.pole9e.grid(row = 5, column = 9)
        self.pole10e = Entry(self, width = 2, font=("Courier", 20))
        self.pole10e.grid(row = 5, column = 10)
        self.pole11e = Entry(self, width = 2, font=("Courier", 20), bg = 'yellow')
        self.pole11e.grid(row = 5, column = 11)
        self.pole12e = Entry(self, width = 2, font=("Courier", 20))
        self.pole12e.grid(row = 5, column = 12)
        self.pole13e = Entry(self, width = 2, font=("Courier", 20))
        self.pole13e.grid(row = 5, column = 13)
        self.pole14e = Entry(self, width = 2, font=("Courier", 20))
        self.pole14e.grid(row = 5, column = 14)
        self.pole15e = Entry(self, width = 2, font=("Courier", 20))
        self.pole15e.grid(row = 5, column = 15)
            #Wiersz F
        self.pole1f = Entry(self, width = 2, font=("Courier", 20))
        self.pole1f.grid(row = 6, column = 1)
        self.pole2f = Entry(self, width = 2, font=("Courier", 20), bg = 'cornflower blue')
        self.pole2f.grid(row = 6, column = 2)
        self.pole3f = Entry(self, width = 2, font=("Courier", 20))
        self.pole3f.grid(row = 6, column = 3)
        self.pole4f = Entry(self, width = 2, font=("Courier", 20))
        self.pole4f.grid(row = 6, column = 4)
        self.pole5f = Entry(self, width = 2, font=("Courier", 20))
        self.pole5f.grid(row = 6, column = 5)
        self.pole6f = Entry(self, width = 2, font=("Courier", 20), bg = 'cornflower blue')
        self.pole6f.grid(row = 6, column = 6)
        self.pole7f = Entry(self, width = 2, font=("Courier", 20))
        self.pole7f.grid(row = 6, column = 7)
        self.pole8f = Entry(self, width = 2, font=("Courier", 20))
        self.pole8f.grid(row = 6, column = 8)
        self.pole9f = Entry(self, width = 2, font=("Courier", 20))
        self.pole9f.grid(row = 6, column = 9)
        self.pole10f = Entry(self, width = 2, font=("Courier", 20), bg = 'cornflower blue')
        self.pole10f.grid(row = 6, column = 10)
        self.pole11f = Entry(self, width = 2, font=("Courier", 20))
        self.pole11f.grid(row = 6, column = 11)
        self.pole12f = Entry(self, width = 2, font=("Courier", 20))
        self.pole12f.grid(row = 6, column = 12)
        self.pole13f = Entry(self, width = 2, font=("Courier", 20))
        self.pole13f.grid(row = 6, column = 13)
        self.pole14f = Entry(self, width = 2, font=("Courier", 20), bg = 'cornflower blue')
        self.pole14f.grid(row = 6, column = 14)
        self.pole15f = Entry(self, width = 2, font=("Courier", 20))
        self.pole15f.grid(row = 6, column = 15)
            #Wiersz G
        self.pole1g = Entry(self, width = 2, font=("Courier", 20))
        self.pole1g.grid(row = 7, column = 1)
        self.pole2g = Entry(self, width = 2, font=("Courier", 20))
        self.pole2g.grid(row = 7, column = 2)
        self.pole3g = Entry(self, width = 2, font=("Courier", 20), bg = 'cyan')
        self.pole3g.grid(row = 7, column = 3)
        self.pole4g = Entry(self, width = 2, font=("Courier", 20))
        self.pole4g.grid(row = 7, column = 4)
        self.pole5g = Entry(self, width = 2, font=("Courier", 20))
        self.pole5g.grid(row = 7, column = 5)
        self.pole6g = Entry(self, width = 2, font=("Courier", 20))
        self.pole6g.grid(row = 7, column = 6)
        self.pole7g = Entry(self, width = 2, font=("Courier", 20), bg = 'cyan')
        self.pole7g.grid(row = 7, column = 7)
        self.pole8g = Entry(self, width = 2, font=("Courier", 20))
        self.pole8g.grid(row = 7, column = 8)
        self.pole9g = Entry(self, width = 2, font=("Courier", 20), bg = 'cyan')
        self.pole9g.grid(row = 7, column = 9)
        self.pole10g = Entry(self, width = 2, font=("Courier", 20))
        self.pole10g.grid(row = 7, column = 10)
        self.pole11g = Entry(self, width = 2, font=("Courier", 20))
        self.pole11g.grid(row = 7, column = 11)
        self.pole12g = Entry(self, width = 2, font=("Courier", 20))
        self.pole12g.grid(row = 7, column = 12)
        self.pole13g = Entry(self, width = 2, font=("Courier", 20), bg = 'cyan')
        self.pole13g.grid(row = 7, column = 13)
        self.pole14g = Entry(self, width = 2, font=("Courier", 20))
        self.pole14g.grid(row = 7, column = 14)
        self.pole15g = Entry(self, width = 2, font=("Courier", 20))
        self.pole15g.grid(row = 7, column = 15)
            #Wiersz H
        self.pole1h = Entry(self, width = 2, font=("Courier", 20), bg = 'red')
        self.pole1h.grid(row = 8, column = 1)
        self.pole2h = Entry(self, width = 2, font=("Courier", 20))
        self.pole2h.grid(row = 8, column = 2)
        self.pole3h = Entry(self, width = 2, font=("Courier", 20))
        self.pole3h.grid(row = 8, column = 3)
        self.pole4h = Entry(self, width = 2, font=("Courier", 20), bg = 'cyan')
        self.pole4h.grid(row = 8, column = 4)
        self.pole5h = Entry(self, width = 2, font=("Courier", 20))
        self.pole5h.grid(row = 8, column = 5)
        self.pole6h = Entry(self, width = 2, font=("Courier", 20))
        self.pole6h.grid(row = 8, column = 6)
        self.pole7h = Entry(self, width = 2, font=("Courier", 20))
        self.pole7h.grid(row = 8, column = 7)
        self.pole8h = Entry(self, width = 2, font=("Courier", 20), bg = 'light goldenrod')
        self.pole8h.grid(row = 8, column = 8)
        self.pole9h = Entry(self, width = 2, font=("Courier", 20))
        self.pole9h.grid(row = 8, column = 9)
        self.pole10h = Entry(self, width = 2, font=("Courier", 20))
        self.pole10h.grid(row = 8, column = 10)
        self.pole11h = Entry(self, width = 2, font=("Courier", 20))
        self.pole11h.grid(row = 8, column = 11)
        self.pole12h = Entry(self, width = 2, font=("Courier", 20), bg = 'cyan')
        self.pole12h.grid(row = 8, column = 12)
        self.pole13h = Entry(self, width = 2, font=("Courier", 20))
        self.pole13h.grid(row = 8, column = 13)
        self.pole14h = Entry(self, width = 2, font=("Courier", 20))
        self.pole14h.grid(row = 8, column = 14)
        self.pole15h = Entry(self, width = 2, font=("Courier", 20), bg = 'red')
        self.pole15h.grid(row = 8, column = 15)
            #Wiersz I
        self.pole1i = Entry(self, width = 2, font=("Courier", 20))
        self.pole1i.grid(row = 9, column = 1)
        self.pole2i = Entry(self, width = 2, font=("Courier", 20))
        self.pole2i.grid(row = 9, column = 2)
        self.pole3i = Entry(self, width = 2, font=("Courier", 20), bg = 'cyan')
        self.pole3i.grid(row = 9, column = 3)
        self.pole4i = Entry(self, width = 2, font=("Courier", 20))
        self.pole4i.grid(row = 9, column = 4)
        self.pole5i = Entry(self, width = 2, font=("Courier", 20))
        self.pole5i.grid(row = 9, column = 5)
        self.pole6i = Entry(self, width = 2, font=("Courier", 20))
        self.pole6i.grid(row = 9, column = 6)
        self.pole7i = Entry(self, width = 2, font=("Courier", 20), bg = 'cyan')
        self.pole7i.grid(row = 9, column = 7)
        self.pole8i = Entry(self, width = 2, font=("Courier", 20))
        self.pole8i.grid(row = 9, column = 8)
        self.pole9i = Entry(self, width = 2, font=("Courier", 20), bg = 'cyan')
        self.pole9i.grid(row = 9, column = 9)
        self.pole10i = Entry(self, width = 2, font=("Courier", 20))
        self.pole10i.grid(row = 9, column = 10)
        self.pole11i = Entry(self, width = 2, font=("Courier", 20))
        self.pole11i.grid(row = 9, column = 11)
        self.pole12i = Entry(self, width = 2, font=("Courier", 20))
        self.pole12i.grid(row = 9, column = 12)
        self.pole13i = Entry(self, width = 2, font=("Courier", 20), bg = 'cyan')
        self.pole13i.grid(row = 9, column = 13)
        self.pole14i = Entry(self, width = 2, font=("Courier", 20))
        self.pole14i.grid(row = 9, column = 14)
        self.pole15i = Entry(self, width = 2, font=("Courier", 20))
        self.pole15i.grid(row = 9, column = 15)
            #Wiersz J
        self.pole1j = Entry(self, width = 2, font=("Courier", 20))
        self.pole1j.grid(row = 10, column = 1)
        self.pole2j = Entry(self, width = 2, font=("Courier", 20), bg = 'cornflower blue')
        self.pole2j.grid(row = 10, column = 2)
        self.pole3j = Entry(self, width = 2, font=("Courier", 20))
        self.pole3j.grid(row = 10, column = 3)
        self.pole4j = Entry(self, width = 2, font=("Courier", 20))
        self.pole4j.grid(row = 10, column = 4)
        self.pole5j = Entry(self, width = 2, font=("Courier", 20))
        self.pole5j.grid(row = 10, column = 5)
        self.pole6j = Entry(self, width = 2, font=("Courier", 20), bg = 'cornflower blue')
        self.pole6j.grid(row = 10, column = 6)
        self.pole7j = Entry(self, width = 2, font=("Courier", 20))
        self.pole7j.grid(row = 10, column = 7)
        self.pole8j = Entry(self, width = 2, font=("Courier", 20))
        self.pole8j.grid(row = 10, column = 8)
        self.pole9j = Entry(self, width = 2, font=("Courier", 20))
        self.pole9j.grid(row = 10, column = 9)
        self.pole10j = Entry(self, width = 2, font=("Courier", 20), bg = 'cornflower blue')
        self.pole10j.grid(row = 10, column = 10)
        self.pole11j = Entry(self, width = 2, font=("Courier", 20))
        self.pole11j.grid(row = 10, column = 11)
        self.pole12j = Entry(self, width = 2, font=("Courier", 20))
        self.pole12j.grid(row = 10, column = 12)
        self.pole13j = Entry(self, width = 2, font=("Courier", 20))
        self.pole13j.grid(row = 10, column = 13)
        self.pole14j = Entry(self, width = 2, font=("Courier", 20), bg = 'cornflower blue')
        self.pole14j.grid(row = 10, column = 14)
        self.pole15j = Entry(self, width = 2, font=("Courier", 20))
        self.pole15j.grid(row = 10, column = 15)
            #Wiersz K
        self.pole1k = Entry(self, width = 2, font=("Courier", 20))
        self.pole1k.grid(row = 11, column = 1)
        self.pole2k = Entry(self, width = 2, font=("Courier", 20))
        self.pole2k.grid(row = 11, column = 2)
        self.pole3k = Entry(self, width = 2, font=("Courier", 20))
        self.pole3k.grid(row = 11, column = 3)
        self.pole4k = Entry(self, width = 2, font=("Courier", 20))
        self.pole4k.grid(row = 11, column = 4)
        self.pole5k = Entry(self, width = 2, font=("Courier", 20), bg = 'yellow')
        self.pole5k.grid(row = 11, column = 5)
        self.pole6k = Entry(self, width = 2, font=("Courier", 20))
        self.pole6k.grid(row = 11, column = 6)
        self.pole7k = Entry(self, width = 2, font=("Courier", 20))
        self.pole7k.grid(row = 11, column = 7)
        self.pole8k = Entry(self, width = 2, font=("Courier", 20))
        self.pole8k.grid(row = 11, column = 8)
        self.pole9k = Entry(self, width = 2, font=("Courier", 20))
        self.pole9k.grid(row = 11, column = 9)
        self.pole10k = Entry(self, width = 2, font=("Courier", 20))
        self.pole10k.grid(row = 11, column = 10)
        self.pole11k = Entry(self, width = 2, font=("Courier", 20), bg = 'yellow')
        self.pole11k.grid(row = 11, column = 11)
        self.pole12k = Entry(self, width = 2, font=("Courier", 20))
        self.pole12k.grid(row = 11, column = 12)
        self.pole13k = Entry(self, width = 2, font=("Courier", 20))
        self.pole13k.grid(row = 11, column = 13)
        self.pole14k = Entry(self, width = 2, font=("Courier", 20))
        self.pole14k.grid(row = 11, column = 14)
        self.pole15k = Entry(self, width = 2, font=("Courier", 20))
        self.pole15k.grid(row = 11, column = 15)
            #Wiersz L
        self.pole1l = Entry(self, width = 2, font=("Courier", 20), bg = 'cyan')
        self.pole1l.grid(row = 12, column = 1)
        self.pole2l = Entry(self, width = 2, font=("Courier", 20))
        self.pole2l.grid(row = 12, column = 2)
        self.pole3l = Entry(self, width = 2, font=("Courier", 20))
        self.pole3l.grid(row = 12, column = 3)
        self.pole4l = Entry(self, width = 2, font=("Courier", 20), bg = 'yellow')
        self.pole4l.grid(row = 12, column = 4)
        self.pole5l = Entry(self, width = 2, font=("Courier", 20))
        self.pole5l.grid(row = 12, column = 5)
        self.pole6l = Entry(self, width = 2, font=("Courier", 20))
        self.pole6l.grid(row = 12, column = 6)
        self.pole7l = Entry(self, width = 2, font=("Courier", 20))
        self.pole7l.grid(row = 12, column = 7)
        self.pole8l = Entry(self, width = 2, font=("Courier", 20), bg = 'cyan')
        self.pole8l.grid(row = 12, column = 8)
        self.pole9l = Entry(self, width = 2, font=("Courier", 20))
        self.pole9l.grid(row = 12, column = 9)
        self.pole10l = Entry(self, width = 2, font=("Courier", 20))
        self.pole10l.grid(row = 12, column = 10)
        self.pole11l = Entry(self, width = 2, font=("Courier", 20))
        self.pole11l.grid(row = 12, column = 11)
        self.pole12l = Entry(self, width = 2, font=("Courier", 20), bg = 'yellow')
        self.pole12l.grid(row = 12, column = 12)
        self.pole13l = Entry(self, width = 2, font=("Courier", 20))
        self.pole13l.grid(row = 12, column = 13)
        self.pole14l = Entry(self, width = 2, font=("Courier", 20))
        self.pole14l.grid(row = 12, column = 14)
        self.pole15l = Entry(self, width = 2, font=("Courier", 20), bg = 'cyan')
        self.pole15l.grid(row = 12, column = 15)
            #Wiersz M
        self.pole1m = Entry(self, width = 2, font=("Courier", 20))
        self.pole1m.grid(row = 13, column = 1)
        self.pole2m = Entry(self, width = 2, font=("Courier", 20))
        self.pole2m.grid(row = 13, column = 2)
        self.pole3m = Entry(self, width = 2, font=("Courier", 20), bg = 'yellow')
        self.pole3m.grid(row = 13, column = 3)
        self.pole4m = Entry(self, width = 2, font=("Courier", 20))
        self.pole4m.grid(row = 13, column = 4)
        self.pole5m = Entry(self, width = 2, font=("Courier", 20))
        self.pole5m.grid(row = 13, column = 5)
        self.pole6m = Entry(self, width = 2, font=("Courier", 20))
        self.pole6m.grid(row = 13, column = 6)
        self.pole7m = Entry(self, width = 2, font=("Courier", 20), bg = 'cyan')
        self.pole7m.grid(row = 13, column = 7)
        self.pole8m = Entry(self, width = 2, font=("Courier", 20))
        self.pole8m.grid(row = 13, column = 8)
        self.pole9m = Entry(self, width = 2, font=("Courier", 20), bg = 'cyan')
        self.pole9m.grid(row = 13, column = 9)
        self.pole10m = Entry(self, width = 2, font=("Courier", 20))
        self.pole10m.grid(row = 13, column = 10)
        self.pole11m = Entry(self, width = 2, font=("Courier", 20))
        self.pole11m.grid(row = 13, column = 11)
        self.pole12m = Entry(self, width = 2, font=("Courier", 20))
        self.pole12m.grid(row = 13, column = 12)
        self.pole13m = Entry(self, width = 2, font=("Courier", 20), bg = 'yellow')
        self.pole13m.grid(row = 13, column = 13)
        self.pole14m = Entry(self, width = 2, font=("Courier", 20))
        self.pole14m.grid(row = 13, column = 14)
        self.pole15m = Entry(self, width = 2, font=("Courier", 20))
        self.pole15m.grid(row = 13, column = 15)
            #Wiersz N
        self.pole1n = Entry(self, width = 2, font=("Courier", 20))
        self.pole1n.grid(row = 14, column = 1)
        self.pole2n = Entry(self, width = 2, font=("Courier", 20), bg = 'yellow')
        self.pole2n.grid(row = 14, column = 2)
        self.pole3n = Entry(self, width = 2, font=("Courier", 20))
        self.pole3n.grid(row = 14, column = 3)
        self.pole4n = Entry(self, width = 2, font=("Courier", 20))
        self.pole4n.grid(row = 14, column = 4)
        self.pole5n = Entry(self, width = 2, font=("Courier", 20))
        self.pole5n.grid(row = 14, column = 5)
        self.pole6n = Entry(self, width = 2, font=("Courier", 20), bg = 'cornflower blue')
        self.pole6n.grid(row = 14, column = 6)
        self.pole7n = Entry(self, width = 2, font=("Courier", 20))
        self.pole7n.grid(row = 14, column = 7)
        self.pole8n = Entry(self, width = 2, font=("Courier", 20))
        self.pole8n.grid(row = 14, column = 8)
        self.pole9n = Entry(self, width = 2, font=("Courier", 20))
        self.pole9n.grid(row = 14, column = 9)
        self.pole10n = Entry(self, width = 2, font=("Courier", 20), bg = 'cornflower blue')
        self.pole10n.grid(row = 14, column = 10)
        self.pole11n = Entry(self, width = 2, font=("Courier", 20))
        self.pole11n.grid(row = 14, column = 11)
        self.pole12n = Entry(self, width = 2, font=("Courier", 20))
        self.pole12n.grid(row = 14, column = 12)
        self.pole13n = Entry(self, width = 2, font=("Courier", 20))
        self.pole13n.grid(row = 14, column = 13)
        self.pole14n = Entry(self, width = 2, font=("Courier", 20), bg = 'yellow')
        self.pole14n.grid(row = 14, column = 14)
        self.pole15n = Entry(self, width = 2, font=("Courier", 20))
        self.pole15n.grid(row = 14, column = 15)
            #Wiersz O
        self.pole1o = Entry(self, width = 2, font=("Courier", 20), bg = 'red')
        self.pole1o.grid(row = 15, column = 1)
        self.pole2o = Entry(self, width = 2, font=("Courier", 20))
        self.pole2o.grid(row = 15, column = 2)
        self.pole3o = Entry(self, width = 2, font=("Courier", 20))
        self.pole3o.grid(row = 15, column = 3)
        self.pole4o = Entry(self, width = 2, font=("Courier", 20), bg = 'cyan')
        self.pole4o.grid(row = 15, column = 4)
        self.pole5o = Entry(self, width = 2, font=("Courier", 20))
        self.pole5o.grid(row = 15, column = 5)
        self.pole6o = Entry(self, width = 2, font=("Courier", 20))
        self.pole6o.grid(row = 15, column = 6)
        self.pole7o = Entry(self, width = 2, font=("Courier", 20))
        self.pole7o.grid(row = 15, column = 7)
        self.pole8o = Entry(self, width = 2, font=("Courier", 20), bg = 'red')
        self.pole8o.grid(row = 15, column = 8)
        self.pole9o = Entry(self, width = 2, font=("Courier", 20))
        self.pole9o.grid(row = 15, column = 9)
        self.pole10o = Entry(self, width = 2, font=("Courier", 20))
        self.pole10o.grid(row = 15, column = 10)
        self.pole11o = Entry(self, width = 2, font=("Courier", 20))
        self.pole11o.grid(row = 15, column = 11)
        self.pole12o = Entry(self, width = 2, font=("Courier", 20), bg = 'cyan')
        self.pole12o.grid(row = 15, column = 12)
        self.pole13o = Entry(self, width = 2, font=("Courier", 20))
        self.pole13o.grid(row = 15, column = 13)
        self.pole14o = Entry(self, width = 2, font=("Courier", 20))
        self.pole14o.grid(row = 15, column = 14)
        self.pole15o = Entry(self, width = 2, font=("Courier", 20), bg = 'red')
        self.pole15o.grid(row = 15, column = 15)
        #Przycisk do dodawania nowych wyrazów
        przycisk_dodaj_wyraz = Button(self, command = self.dodaj_wyraz).grid(row = 0, column = 16)

    def dodaj_wyraz(self):
        """Dodaje wyraz do puli wyrazów."""
        for litera in self.POLA:
            self.litery.append(litera.get())
        print("Czerwony:",self.litery.count("c"))
        print("Teal:",self.litery.count("t"))
        print("Żółty:",self.litery.count("y"))
        print("Niebieski:",self.litery.count("n"))
        print("Biały:",self.litery.count("b"))
        print("Złoty:",self.litery.count("z"))

root = Tk()
root.title("Kalkulator")
root.geometry("700x580")

app = Application(root)

root.mainloop()
